// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/address.proto

package /src/java;

public final class AddressOuterClass {
  private AddressOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string buildingName = 1;</code>
     * @return The buildingName.
     */
    java.lang.String getBuildingName();
    /**
     * <code>string buildingName = 1;</code>
     * @return The bytes for buildingName.
     */
    com.google.protobuf.ByteString
        getBuildingNameBytes();

    /**
     * <code>string streetName = 2;</code>
     * @return The streetName.
     */
    java.lang.String getStreetName();
    /**
     * <code>string streetName = 2;</code>
     * @return The bytes for streetName.
     */
    com.google.protobuf.ByteString
        getStreetNameBytes();

    /**
     * <code>string areaName = 3;</code>
     * @return The areaName.
     */
    java.lang.String getAreaName();
    /**
     * <code>string areaName = 3;</code>
     * @return The bytes for areaName.
     */
    com.google.protobuf.ByteString
        getAreaNameBytes();

    /**
     * <code>string cityName = 4;</code>
     * @return The cityName.
     */
    java.lang.String getCityName();
    /**
     * <code>string cityName = 4;</code>
     * @return The bytes for cityName.
     */
    com.google.protobuf.ByteString
        getCityNameBytes();

    /**
     * <code>string districtName = 5;</code>
     * @return The districtName.
     */
    java.lang.String getDistrictName();
    /**
     * <code>string districtName = 5;</code>
     * @return The bytes for districtName.
     */
    com.google.protobuf.ByteString
        getDistrictNameBytes();

    /**
     * <code>string stateName = 6;</code>
     * @return The stateName.
     */
    java.lang.String getStateName();
    /**
     * <code>string stateName = 6;</code>
     * @return The bytes for stateName.
     */
    com.google.protobuf.ByteString
        getStateNameBytes();

    /**
     * <code>string countryName = 7;</code>
     * @return The countryName.
     */
    java.lang.String getCountryName();
    /**
     * <code>string countryName = 7;</code>
     * @return The bytes for countryName.
     */
    com.google.protobuf.ByteString
        getCountryNameBytes();

    /**
     * <code>int32 pinCode = 8;</code>
     * @return The pinCode.
     */
    int getPinCode();
  }
  /**
   * Protobuf type {@code Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      buildingName_ = "";
      streetName_ = "";
      areaName_ = "";
      cityName_ = "";
      districtName_ = "";
      stateName_ = "";
      countryName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return /src/java.AddressOuterClass.internal_static_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return /src/java.AddressOuterClass.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              /src/java.AddressOuterClass.Address.class, /src/java.AddressOuterClass.Address.Builder.class);
    }

    public static final int BUILDINGNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object buildingName_ = "";
    /**
     * <code>string buildingName = 1;</code>
     * @return The buildingName.
     */
    @java.lang.Override
    public java.lang.String getBuildingName() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingName_ = s;
        return s;
      }
    }
    /**
     * <code>string buildingName = 1;</code>
     * @return The bytes for buildingName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildingNameBytes() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STREETNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object streetName_ = "";
    /**
     * <code>string streetName = 2;</code>
     * @return The streetName.
     */
    @java.lang.Override
    public java.lang.String getStreetName() {
      java.lang.Object ref = streetName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetName_ = s;
        return s;
      }
    }
    /**
     * <code>string streetName = 2;</code>
     * @return The bytes for streetName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetNameBytes() {
      java.lang.Object ref = streetName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AREANAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object areaName_ = "";
    /**
     * <code>string areaName = 3;</code>
     * @return The areaName.
     */
    @java.lang.Override
    public java.lang.String getAreaName() {
      java.lang.Object ref = areaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaName_ = s;
        return s;
      }
    }
    /**
     * <code>string areaName = 3;</code>
     * @return The bytes for areaName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAreaNameBytes() {
      java.lang.Object ref = areaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITYNAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cityName_ = "";
    /**
     * <code>string cityName = 4;</code>
     * @return The cityName.
     */
    @java.lang.Override
    public java.lang.String getCityName() {
      java.lang.Object ref = cityName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cityName_ = s;
        return s;
      }
    }
    /**
     * <code>string cityName = 4;</code>
     * @return The bytes for cityName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityNameBytes() {
      java.lang.Object ref = cityName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISTRICTNAME_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object districtName_ = "";
    /**
     * <code>string districtName = 5;</code>
     * @return The districtName.
     */
    @java.lang.Override
    public java.lang.String getDistrictName() {
      java.lang.Object ref = districtName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        districtName_ = s;
        return s;
      }
    }
    /**
     * <code>string districtName = 5;</code>
     * @return The bytes for districtName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDistrictNameBytes() {
      java.lang.Object ref = districtName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        districtName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATENAME_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stateName_ = "";
    /**
     * <code>string stateName = 6;</code>
     * @return The stateName.
     */
    @java.lang.Override
    public java.lang.String getStateName() {
      java.lang.Object ref = stateName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stateName_ = s;
        return s;
      }
    }
    /**
     * <code>string stateName = 6;</code>
     * @return The bytes for stateName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateNameBytes() {
      java.lang.Object ref = stateName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRYNAME_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object countryName_ = "";
    /**
     * <code>string countryName = 7;</code>
     * @return The countryName.
     */
    @java.lang.Override
    public java.lang.String getCountryName() {
      java.lang.Object ref = countryName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryName_ = s;
        return s;
      }
    }
    /**
     * <code>string countryName = 7;</code>
     * @return The bytes for countryName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryNameBytes() {
      java.lang.Object ref = countryName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PINCODE_FIELD_NUMBER = 8;
    private int pinCode_ = 0;
    /**
     * <code>int32 pinCode = 8;</code>
     * @return The pinCode.
     */
    @java.lang.Override
    public int getPinCode() {
      return pinCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buildingName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buildingName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, streetName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(areaName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, areaName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cityName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cityName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(districtName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, districtName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stateName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stateName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, countryName_);
      }
      if (pinCode_ != 0) {
        output.writeInt32(8, pinCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buildingName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buildingName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, streetName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(areaName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, areaName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cityName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cityName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(districtName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, districtName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stateName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, stateName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, countryName_);
      }
      if (pinCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, pinCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof /src/java.AddressOuterClass.Address)) {
        return super.equals(obj);
      }
      /src/java.AddressOuterClass.Address other = (/src/java.AddressOuterClass.Address) obj;

      if (!getBuildingName()
          .equals(other.getBuildingName())) return false;
      if (!getStreetName()
          .equals(other.getStreetName())) return false;
      if (!getAreaName()
          .equals(other.getAreaName())) return false;
      if (!getCityName()
          .equals(other.getCityName())) return false;
      if (!getDistrictName()
          .equals(other.getDistrictName())) return false;
      if (!getStateName()
          .equals(other.getStateName())) return false;
      if (!getCountryName()
          .equals(other.getCountryName())) return false;
      if (getPinCode()
          != other.getPinCode()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDINGNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingName().hashCode();
      hash = (37 * hash) + STREETNAME_FIELD_NUMBER;
      hash = (53 * hash) + getStreetName().hashCode();
      hash = (37 * hash) + AREANAME_FIELD_NUMBER;
      hash = (53 * hash) + getAreaName().hashCode();
      hash = (37 * hash) + CITYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCityName().hashCode();
      hash = (37 * hash) + DISTRICTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDistrictName().hashCode();
      hash = (37 * hash) + STATENAME_FIELD_NUMBER;
      hash = (53 * hash) + getStateName().hashCode();
      hash = (37 * hash) + COUNTRYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCountryName().hashCode();
      hash = (37 * hash) + PINCODE_FIELD_NUMBER;
      hash = (53 * hash) + getPinCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static /src/java.AddressOuterClass.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static /src/java.AddressOuterClass.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static /src/java.AddressOuterClass.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static /src/java.AddressOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(/src/java.AddressOuterClass.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        /src/java.AddressOuterClass.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return /src/java.AddressOuterClass.internal_static_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return /src/java.AddressOuterClass.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                /src/java.AddressOuterClass.Address.class, /src/java.AddressOuterClass.Address.Builder.class);
      }

      // Construct using /src/java.AddressOuterClass.Address.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        buildingName_ = "";
        streetName_ = "";
        areaName_ = "";
        cityName_ = "";
        districtName_ = "";
        stateName_ = "";
        countryName_ = "";
        pinCode_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return /src/java.AddressOuterClass.internal_static_Address_descriptor;
      }

      @java.lang.Override
      public /src/java.AddressOuterClass.Address getDefaultInstanceForType() {
        return /src/java.AddressOuterClass.Address.getDefaultInstance();
      }

      @java.lang.Override
      public /src/java.AddressOuterClass.Address build() {
        /src/java.AddressOuterClass.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public /src/java.AddressOuterClass.Address buildPartial() {
        /src/java.AddressOuterClass.Address result = new /src/java.AddressOuterClass.Address(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(/src/java.AddressOuterClass.Address result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.buildingName_ = buildingName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.streetName_ = streetName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.areaName_ = areaName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cityName_ = cityName_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.districtName_ = districtName_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.stateName_ = stateName_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.countryName_ = countryName_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.pinCode_ = pinCode_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof /src/java.AddressOuterClass.Address) {
          return mergeFrom((/src/java.AddressOuterClass.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(/src/java.AddressOuterClass.Address other) {
        if (other == /src/java.AddressOuterClass.Address.getDefaultInstance()) return this;
        if (!other.getBuildingName().isEmpty()) {
          buildingName_ = other.buildingName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getStreetName().isEmpty()) {
          streetName_ = other.streetName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAreaName().isEmpty()) {
          areaName_ = other.areaName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getCityName().isEmpty()) {
          cityName_ = other.cityName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getDistrictName().isEmpty()) {
          districtName_ = other.districtName_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getStateName().isEmpty()) {
          stateName_ = other.stateName_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getCountryName().isEmpty()) {
          countryName_ = other.countryName_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getPinCode() != 0) {
          setPinCode(other.getPinCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                buildingName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                streetName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                areaName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                cityName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                districtName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                stateName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                countryName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                pinCode_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object buildingName_ = "";
      /**
       * <code>string buildingName = 1;</code>
       * @return The buildingName.
       */
      public java.lang.String getBuildingName() {
        java.lang.Object ref = buildingName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string buildingName = 1;</code>
       * @return The bytes for buildingName.
       */
      public com.google.protobuf.ByteString
          getBuildingNameBytes() {
        java.lang.Object ref = buildingName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string buildingName = 1;</code>
       * @param value The buildingName to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        buildingName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string buildingName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingName() {
        buildingName_ = getDefaultInstance().getBuildingName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string buildingName = 1;</code>
       * @param value The bytes for buildingName to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        buildingName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object streetName_ = "";
      /**
       * <code>string streetName = 2;</code>
       * @return The streetName.
       */
      public java.lang.String getStreetName() {
        java.lang.Object ref = streetName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streetName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string streetName = 2;</code>
       * @return The bytes for streetName.
       */
      public com.google.protobuf.ByteString
          getStreetNameBytes() {
        java.lang.Object ref = streetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string streetName = 2;</code>
       * @param value The streetName to set.
       * @return This builder for chaining.
       */
      public Builder setStreetName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        streetName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string streetName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreetName() {
        streetName_ = getDefaultInstance().getStreetName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string streetName = 2;</code>
       * @param value The bytes for streetName to set.
       * @return This builder for chaining.
       */
      public Builder setStreetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        streetName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object areaName_ = "";
      /**
       * <code>string areaName = 3;</code>
       * @return The areaName.
       */
      public java.lang.String getAreaName() {
        java.lang.Object ref = areaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          areaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string areaName = 3;</code>
       * @return The bytes for areaName.
       */
      public com.google.protobuf.ByteString
          getAreaNameBytes() {
        java.lang.Object ref = areaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          areaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string areaName = 3;</code>
       * @param value The areaName to set.
       * @return This builder for chaining.
       */
      public Builder setAreaName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        areaName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string areaName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAreaName() {
        areaName_ = getDefaultInstance().getAreaName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string areaName = 3;</code>
       * @param value The bytes for areaName to set.
       * @return This builder for chaining.
       */
      public Builder setAreaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        areaName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object cityName_ = "";
      /**
       * <code>string cityName = 4;</code>
       * @return The cityName.
       */
      public java.lang.String getCityName() {
        java.lang.Object ref = cityName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cityName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cityName = 4;</code>
       * @return The bytes for cityName.
       */
      public com.google.protobuf.ByteString
          getCityNameBytes() {
        java.lang.Object ref = cityName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cityName = 4;</code>
       * @param value The cityName to set.
       * @return This builder for chaining.
       */
      public Builder setCityName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cityName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string cityName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCityName() {
        cityName_ = getDefaultInstance().getCityName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string cityName = 4;</code>
       * @param value The bytes for cityName to set.
       * @return This builder for chaining.
       */
      public Builder setCityNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cityName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object districtName_ = "";
      /**
       * <code>string districtName = 5;</code>
       * @return The districtName.
       */
      public java.lang.String getDistrictName() {
        java.lang.Object ref = districtName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          districtName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string districtName = 5;</code>
       * @return The bytes for districtName.
       */
      public com.google.protobuf.ByteString
          getDistrictNameBytes() {
        java.lang.Object ref = districtName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          districtName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string districtName = 5;</code>
       * @param value The districtName to set.
       * @return This builder for chaining.
       */
      public Builder setDistrictName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        districtName_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string districtName = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistrictName() {
        districtName_ = getDefaultInstance().getDistrictName();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string districtName = 5;</code>
       * @param value The bytes for districtName to set.
       * @return This builder for chaining.
       */
      public Builder setDistrictNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        districtName_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object stateName_ = "";
      /**
       * <code>string stateName = 6;</code>
       * @return The stateName.
       */
      public java.lang.String getStateName() {
        java.lang.Object ref = stateName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stateName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stateName = 6;</code>
       * @return The bytes for stateName.
       */
      public com.google.protobuf.ByteString
          getStateNameBytes() {
        java.lang.Object ref = stateName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stateName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stateName = 6;</code>
       * @param value The stateName to set.
       * @return This builder for chaining.
       */
      public Builder setStateName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stateName_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string stateName = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStateName() {
        stateName_ = getDefaultInstance().getStateName();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string stateName = 6;</code>
       * @param value The bytes for stateName to set.
       * @return This builder for chaining.
       */
      public Builder setStateNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stateName_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object countryName_ = "";
      /**
       * <code>string countryName = 7;</code>
       * @return The countryName.
       */
      public java.lang.String getCountryName() {
        java.lang.Object ref = countryName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string countryName = 7;</code>
       * @return The bytes for countryName.
       */
      public com.google.protobuf.ByteString
          getCountryNameBytes() {
        java.lang.Object ref = countryName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string countryName = 7;</code>
       * @param value The countryName to set.
       * @return This builder for chaining.
       */
      public Builder setCountryName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        countryName_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string countryName = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryName() {
        countryName_ = getDefaultInstance().getCountryName();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string countryName = 7;</code>
       * @param value The bytes for countryName to set.
       * @return This builder for chaining.
       */
      public Builder setCountryNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        countryName_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private int pinCode_ ;
      /**
       * <code>int32 pinCode = 8;</code>
       * @return The pinCode.
       */
      @java.lang.Override
      public int getPinCode() {
        return pinCode_;
      }
      /**
       * <code>int32 pinCode = 8;</code>
       * @param value The pinCode to set.
       * @return This builder for chaining.
       */
      public Builder setPinCode(int value) {
        
        pinCode_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pinCode = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPinCode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        pinCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final /src/java.AddressOuterClass.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new /src/java.AddressOuterClass.Address();
    }

    public static /src/java.AddressOuterClass.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public /src/java.AddressOuterClass.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/address.proto\"\246\001\n\007Address\022\024\n\014bui" +
      "ldingName\030\001 \001(\t\022\022\n\nstreetName\030\002 \001(\t\022\020\n\010a" +
      "reaName\030\003 \001(\t\022\020\n\010cityName\030\004 \001(\t\022\024\n\014distr" +
      "ictName\030\005 \001(\t\022\021\n\tstateName\030\006 \001(\t\022\023\n\013coun" +
      "tryName\030\007 \001(\t\022\017\n\007pinCode\030\010 \001(\005B\024\n\t/src/j" +
      "avaZ\007/src/gob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "BuildingName", "StreetName", "AreaName", "CityName", "DistrictName", "StateName", "CountryName", "PinCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
