# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/address.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/address.proto\"\xa6\x01\n\x07\x41\x64\x64ress\x12\x14\n\x0c\x62uildingName\x18\x01 \x01(\t\x12\x12\n\nstreetName\x18\x02 \x01(\t\x12\x10\n\x08\x61reaName\x18\x03 \x01(\t\x12\x10\n\x08\x63ityName\x18\x04 \x01(\t\x12\x14\n\x0c\x64istrictName\x18\x05 \x01(\t\x12\x11\n\tstateName\x18\x06 \x01(\t\x12\x13\n\x0b\x63ountryName\x18\x07 \x01(\t\x12\x0f\n\x07pinCode\x18\x08 \x01(\x05\x42\x14\n\t/src/javaZ\x07/src/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.address_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\t/src/javaZ\007/src/go'
  _ADDRESS._serialized_start=24
  _ADDRESS._serialized_end=190
# @@protoc_insertion_point(module_scope)
